### ISSUE TITLE
Scope of running process to scan

### ISSUE THREAD

**Issue by DaramG** [KAIST-IS521/2017-Spring#100]
If user runs scanner as a user permission, should scanner check root permission processes?

**Comment by sangkilc** [comment]
You mean by displaying a sudo password prompt? I don't think this is necessary.

**Comment by DaramG** [comment]
스캐너가 유저권한으로 상황되고 있는 상황에서, 이 스캐너들이 루트 권한이나 다른 유저 권한으로 돌고있는 프로세스가 말웨어 인지 스캔을 해야하는 건지 여쭤보고 싶었습니다.

**Comment by sangkilc** [comment]
How can a user process access other processes without root privilege?

**Comment by DaramG** [comment]
But with "ps -ef" command, you can get some information about other processes include root privilege.

**Comment by sangkilc** [comment]
Okay, now I understand your problem. Here is how you do it: list all the running processes (including root-privileged processes), and scan the corresponding files.

**Comment by DaramG** [comment]
But there is some root process which we can not get binaray path

**Comment by sangkilc** [comment]
Sure. You can ignore them.

**Comment by lbh0307** [comment]
You mean if we cannot sure the binary path, we can ignore it?

We can get some information like below

> $ ps -q 1 -o command
COMMAND
/sbin/init

but in general case, we cannot believe this result.

**Comment by soomin-kim** [comment]
What lbh0307 does mean is, a process can modify cmdline file of itself. Right?

**Comment by soomin-kim** [comment]
Sorry for some students, but it's too hard to write my opinion in English.

하지만 AV가 탐지할 수 있는 만큼만 탐지하게 만들어도 괜찮을 것 같은게 그렇게 만들어도 나중에 sudo를 붙이기만 하면 root권한으로 돌고 있는 process들의 바이너리 이름도 알 수 있지 않나요? 사실 cmdline을 보는 것보다 더 확실한 방법이 /proc/[pid]/exe의 link를 읽으면 되는데 이건 권한만 있으면 가능하거든요

**Comment by soomin-kim** [comment]
어차피 이번 숙제의 scope는 AV를 만들 수 있는지를 보는거라고 생각하기 때문에 굳이 root권한이 필요한 경우를 생각해야 하는지 잘 모르겠습니다

**Comment by sangkilc** [comment]
As always, reading manual is helpful :)

Try ```man ps```. You will see the following line:
> Sometimes the process args will be unavailable; when this happens, ps will instead print the executable name in brackets.

I believe what @DaramG originally asked was about such processes that do not have any info about the command line args. And I said you can ignore such cases. Hope this helps.
