### ISSUE TITLE
benign.bin's path confusion

### ISSUE THREAD

**Issue by asdfljh** [KAIST-IS521/2017-Spring#101]
av과제 설명 중
**5. ./benign/Makefile file should produce your benign sample in ./build/benign.bin.**
에서 여기서 말하는 ./build/가 ./benign/build/를 말하는 것인지. scanner가 생기는 ./build/를
말하는 것인지 모르겠어서 질문드립니다.

**Comment by sangkilc** [comment]
```./build/``` means ```PROJROOT/build/```.
