### ISSUE TITLE
[av2-activity] Delete or just unlink

### ISSUE THREAD

**Issue by mfaerevaag** [KAIST-IS521/2017-Spring#103]
After reading the Part 1 of the activity description I am not sure wether I should delete binary or just unlink.

Having the following files:
 - `/tmp/myworm`
 - `/proc/self/exe [ -> /tmp/myworm]`

Should I delete the actual binary worm file (`rm /tmp/myworm`), delete the link (`unlink /proc/self/exe`) or both?

**Comment by sangkilc** [comment]
You should remove the binary, not the link. That's why I call it 'anti-forensic'.

**Comment by mfaerevaag** [comment]
Aha, that makes sense. Thank you!
