### ISSUE TITLE
the new vulnet problem

### ISSUE THREAD

**Issue by mickan921** [KAIST-IS521/2017-Spring#105]
Whenever I send out any commands to the new vulnet

it first gives me a error message saying that command is not found but then it gives me what I want in the next line. For instance:
```
ls
/bin/bash: line 1: checkin: command not found
Makefile
README.md
build
vulnet.c
```

However, it does not have that "/bin/bash: line 1: checkin: command not found" on the original vulnet.
Am I the only one having this problem..?

**Comment by blukat29** [comment]
That does not happen in my is521 vagrant box..

It is possible that "ls" command is aliased or replaced by something else in your bash environment.

Check your `~/.bashrc` or `~/.profile`, `~/.bash_profile` files to see if there is "checkin" string.
