### ISSUE TITLE
Questions about 'pathname'

### ISSUE THREAD

**Issue by alinghi** [KAIST-IS521/2017-Spring#107]
My worm works fine in my system. Except two cases:
1.  pathname contain **한글**
2.  pathname contain **vboxsf**

Little bit specifically when remove binary itself.
When I check using perror.
It prints out 
```bash
Text File Busy
```
But except that 2 cases it works fine.(It means program execute self remove function successfully.) I guess in that case reading pathname of binary get encoding kinda problems. Is anyone have an idea regarding to this?

Thank you.

**Comment by sangkilc** [comment]
The second case makes sense, because host process may try to access the file when you delete it. I have no idea about the first case though.

**Comment by alinghi** [comment]
Thank you.
