### ISSUE TITLE
[debugger-activity] endian of 4-byte value & output format

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/2017-Spring#108]
At this line, `0x1000,0x4000. This line means that your value tracer needs to print out the 4-byte value`

Should we consider this 4-byte value as an integer value? or just 4-byte dump?

And what should be output format of registers and 4-byte memory value?

**Comment by sangkilc** [comment]
Good question. Please see: a20efbc7d3e257cc42199c011d6bbc3813482119.

**Comment by alinghi** [comment]
I have an additional question. What is a name of output CSV file.

**Comment by sangkilc** [comment]
Good question. See: 6e2902275cae26c304c0b91256192038f5f45e3a
