### ISSUE TITLE
[debugger-activity] validity of a program counter(breakpoint address)

### ISSUE THREAD

**Issue by asdfljh** [KAIST-IS521/2017-Spring#116]
1. 과제에서 말하고 있는 program counter의 정의가 (https://en.wikipedia.org/wiki/Program_counter)
와 같다고 봐도 되나요?

2. `Similarly, when there is an invalid address, your tracer should exit with an error
message.`
이 부분에서 주어진 breakpoint address가 정확히 opcode 위치를 가리키고 있지 않은 경우에도 error message를 출력해주어야 하나요?

ex) 0x0804840f <+20>:    68 c0 84 04 08  push   $0x80484c0 일 때, breakpoint address가 0x8048410인 상황

gdb를 이용하여 테스트 했을 때는 실행하는 과정에서 error가 나지 않을 경우, 별도의 error message없이 breakpoint가 걸리지 않고 해당 위치가 0xcc로 바뀐 상태로 실행이 되는데, 이런 경우도 처리해줘야하는지 궁금합니다.

**Comment by sangkilc** [comment]
1. Yes
2. No
