### ISSUE TITLE
[debugger-activity] address randomization

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/2017-Spring#117]
The VM provided by this course supports the address randomization (ASLR) so that each `EIP` changes whenever the executable starts.

Do I need to disable the address randomization by `echo 0 > /proc/sys/kernel/randomize_va_space` for this activity (root privilege is required)?
To evaluate this activity as mentioned in `0424-debugger.tex`, I think the address randomization needs to be disabled.
Otherwise, the expected output can be different even if `tracer` is implemented well.
Do I understand something wrong?

**Comment by sangkilc** [comment]
You are right. TA will disable ASLR when evaluating this homework.
