### ISSUE TITLE
[Notary Program] About the team-Activity

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2017-Spring#122]
According to the program description,
We should make three services ( Notary program, Launcher and Flag updater)

One of our program, Notary program does not take an IP address as an input so we have to use a
fixed IP to run our program for communication.

Should we build our services in one host or  a multiple host(i.e., build a dedicated service per each host)?
One more, Will TA give us a server to run our service? In this case, Should we update the IP statically?

**Comment by JaeseungChoi** [comment]
> Should we build our services in one host or a multiple host(i.e., build a dedicated service per each host)?

Assuming 'host' means VM image to run the service, each team will have one host that runs both "Notary" service and "Launcher" service. Please elaborate your question if your intention was something different.

> One more, Will TA give us a server to run our service? In this case, Should we update the IP statically?

TA team will provide server VMs that will run the service. Could you explain what you mean by "updating IP"? We cannot see which components of these modules need IP update.

**Comment by oxsignal** [comment]
Thanks to make it clear.
