### ISSUE TITLE
[Team Activity] pitfalls in the flag updater

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/2017-Spring#123]
[Team 1]
안녕하세요, 팀원들과의 회의 중 의문점이 생겨 이슈를 남깁니다.
 
flag update 과정에서 메세지에 포함되어 있는 정보는 signer, newflag, signature 세 가지 인 것으로 주어져있는데요, 
문제는 여기서 해당 플래그 업데이트가 '어느 사이트'에 요청하는 것인지에 대한 정보와 '언제' 요청한 것인지에 대한 정보가 존재하지않아 다음과 같은 문제가 발생할 것으로 생각됩니다.

1. 저희 팀 (bank)에서 플래그 업데이트 메세지를 수신하였다고 가정했을때, 저희는 해당 메세지를 쇼핑몰이나 다른 팀에 재전송함으로써 다른팀의 플래그를 저희의 플래그와 일치시킬 수 있을 것으로 보입니다.
2. 시간에 대한 정보가 포함되어 있지 않기 때문에 과거 만료된 플래그를 전송함으로써 발생할 수 있는 문제가 있지 않을까 생각됩니다.

감사합니다.

**Comment by jchoi2022** [comment]
해당 문제는 조교 팀에서 적절한 네트워크 환경을 구축함으로써 방지하도록 하겠습니다. 자세한 네트워크 환경은 Checkpoint 주간에 안내드릴 예정이며, 그때까지는 flag update service는 이러한 replay 공격으로부터 안전하다고 가정하고 개발하시면 됩니다.

감사합니다.

This issue discusses the possibility that a malicious player can replay the received flag update message to other team's services, and updating the flag of those services with expired flags.

TA team will handle this issue by appropriate network configuration. The details of network environment will be given in 'Checkpoint' week. Until then you can just assume that flag update service is safe from such a malicious replay attack.

Thank you.
