### ISSUE TITLE
[Team Activity] Team3(Network Operator) web application questions.

### ISSUE THREAD

**Issue by pr0v3rbs** [KAIST-IS521/2017-Spring#124]
The document describe that 'web application takes in a log file as input from a user'.
But not describe about type of method(http request from web application, file name of program argument, user input on terminal, etc...).

1. What type of method do I use to transfer log file from user?

2. Can I use python script language to implement web application?

Thank you.

**Comment by jchoi2022** [comment]
> What type of method do I use to transfer log file from user?

The web service should provide a page that allows users to upload a log file to display. In other words, the file should be taken in via HTTP request.

> Can I use python script language to implement web application?

Yes, you can use any language you prefer.

Thank you.

**Comment by pr0v3rbs** [comment]
Thank you!
