### ISSUE TITLE
[Team Activity] Team2(shopping mall) DBMS question

### ISSUE THREAD

**Issue by nohkwak** [KAIST-IS521/2017-Spring#125]
We discuss the choice of DBMS. 
https://github.com/KAIST-IS521/TeamTwo/issues/18 

We consider MySQL or SQLite. 

From the view of engineering (reference, performance and scalability), 
I think MySQL is more appropriate to Web Service. 
while SQLite is appropriate to the mobile app or small application. 

But in our team activity, 
I find that MySQL is impossible to be set up with the 'make'.
For example, Administrator has to login with root for configuring and making our database and account.
It will be almost impossible only to type 'make'.

한국어로 간단히 요약하자면, 
과제 요구사항인 make 명령만으로 실행이 되게 하려면 
SQLite가 더 적합한 선택이 되겠지만, 
SQLite은 모바일 앱 같은 간단한 경우에 사용하는 것이고, 
(보통 Web service에서는 MySQL도 최소 사양의 DBMS로 취급되는데...) 
Web service를 만들면서 SQLite를 선택한다는 것이 어울리지 않는 것 같아 고민입니다. 
더욱이 secure하게 설치를 해야 한다면 manual한 설정이 필요합니다. 
(ex. root 계정으로 원격 접속 불가 등) 

조교님들께서 수고하시는 것은 알지만, 
make 만으로 설치가 된다는 것이 쉽지 않은 상황입니다.

**Comment by jchoi2022** [comment]
> For example, Administrator has to login with root for configuring and making our database and account.

If your command (in Makefile or shell script) starts with "sudo ...", it will automatically ask for password and try to run with root privilege.

> 더욱이 secure하게 설치를 해야 한다면 manual한 설정이 필요합니다.

Does this 'manual configuration' means editing some configuration file? Then, it can be done with 'sed'  command (https://linux.die.net/man/1/sed). Basically, almost all the actions that does not involve interaction with GUI can be written into shell script or Makefile.

**Comment by nohkwak** [comment]
Yes, I agree with your opinion. 
The reason why I ask is the installation process involves text-based GUI and CLI. 
So I am afraid It might be too heavy although it is possible.

Thank you for your comment.

**Comment by sangkilc** [comment]
It should not be that difficult. Please refer to this as an example: http://stackoverflow.com/questions/7739645/install-mysql-on-ubuntu-without-password-prompt

**Comment by nohkwak** [comment]
The installation process is a bit complicated and my thought seems to be too negative.
 I apologize that I have raised the issue too prematurely.
Thank you for your advice.
