### ISSUE TITLE
[Team activity - TeamThree] SLA checker library 의 역할에 대해

### ISSUE THREAD

**Issue by lbh0307** [KAIST-IS521/2017-Spring#126]
SLA checker library spec을 살펴보면 handshake 가 있습니다.

그런데 handshake를 하려면 서버와 클라이언트 사이에 약속된 프로토콜이 존재해야 하는데,
서버는 각 팀마다 구현을 하므로 현재 통일된 규약이 있는 것 같지 않아 어떻게 해야하는지 궁금합니다.

예를들어 서버가 어떻게 github ID 를 요구하는지 (혹은 클라이언트가 바로 id를 보내야하는 것인지) 인코딩은 어떻게 하고 랜덤 숫자는 어떤 형식으로 주고 받을 것인지 등을 확정지어야 한다고 생각합니다.

**Comment by soomin-kim** [comment]
Handshake Protocol only depends on the decision from the team 3.
Other teams should follow the protocol that is designed by team 3.
