### ISSUE TITLE
[Team Activity] Authentication protocol for Web-app

### ISSUE THREAD

**Issue by lbh0307** [KAIST-IS521/2017-Spring#127]
We (TeamThree) have to make handshake protocol and we are in trouble about handling authentication for web-apps. In document, `handshake` function gets `socketfd` for input. However, we think this cannot be applied for web-app. What should we do?

Please see detail and help us in KAIST-IS521/TeamThree#23

**Comment by JaeseungChoi** [comment]
We discussed the issue with professor, and concluded that teams that build web application will not rely on SLA checker library. Therefore, your team can just consider Bank(Team-1) and Notary(Team-4) while developing the library. Please refer to commit 0e81299c.
