### ISSUE TITLE
[Team Activity] Authentication Man-In-The-Middle

### ISSUE THREAD

**Issue by mfaerevaag** [KAIST-IS521/2017-Spring#129]
In the authentication process there is a possible Man-in-the-Middle attack, as the server does not encrypt its public key before sending. This key can be swapped, therefore allowing adversary to impersonate client and send fraudulent data.

> First, a server asks your github ID. When a user provides their
>ID, the server creates a large random number and sends encrypts the number with the
> user’s public key. The server sends the encrypted data along with its public key ...

Below is the steps of the current authentication process, followed by possible attack.

### Current authentication

1. The server sends encrypted random number and  *unencrypted* server public key

2. Client decrypts random number and sends random number reencrypted with server's public key

3. Server decrypts random number and verifies its the same number

4. Client is now authenticated

### Attack

1. The server sends encrypted random number and  *unencrypted* server public key

        Eve stores server's public key and replaces it with her own

2. Client decrypts random number and sends random number reencrypted with ~~server's~~ Eve's public key

        Eve decrypts random number and reencrypts with server's public key

3. Server decrypts random number and verifies its the same number

4. ~~Client~~ Eve is now authenticated

Further Eve can impersonate server so client will not notice, while doing whatever in client's name with actual server.

### Mitigation

By encrypting the random number concatenated with the server's public key, it is not possible to intercept during transmission. Only change is to concatenate the key with random number before encryption.

**Comment by soomin-kim** [comment]
I think this issue depends on the decision from the team 3.
The authentication protocol given in the document only contains minimal necessary things that must be included in the protocol.

I think that it is good for team 3 to refer this issue.

**Comment by mfaerevaag** [comment]
This authentication process is also used for the flag updater, which is developed independently for every team.

**Comment by soomin-kim** [comment]
We modified the specification of the authentication protocol. Please check it.

**Comment by mfaerevaag** [comment]
Jepp, this prevents the attack, but the description does now not include anything about sending the server's public key.

Maybe if the description was made into a enumerated list it would become more clear? I am worried that the description is not technical enough for a good specification, which will cause problems when the TA's will use their scripts for communicating with each team's flag updater..

**Comment by soomin-kim** [comment]
It is assumed that each team already knows other's public key. That's why the professor said each team should create their own pgp key in the last class.

**Comment by mfaerevaag** [comment]
Ah, that makes sense 👍
