### ISSUE TITLE
[Team Activity] Notarized User in Government

### ISSUE THREAD

**Issue by JeongOhKye** [KAIST-IS521/2017-Spring#130]
TeamFive에서 Government의 BBS기능을 구현중인데 2가지 문의점이 있어서 질문 드립니다.

1. Notarized User

기본적으로 BBS에서 PGP기반의 로그인을 사용하도록 되어있습니다.

근데 추가적으로 authenticate라는 기능이 존재하여 notary service에서 받은
sign된 {USERID, PUBKEY}형식의 json파일을 받아서 notarize user로 올라가게 되는데
notary에서 sign을 받기 위해서도 PGP기반의 인증을 이용합니다.

결국 같은 인증을 방식을 사용하는건데 normal user와 notarized user의 차이가 무엇인지 궁금하네요.

2. Password Login

PGP기반의 로그인 방식을 매번 진행하기에 조금 불편한점이 있는거 같아서...
한번 Authenticate된 사용자에 대해서는 password로그인을 진행하는 방식으로 하려고 하는데
이렇게 구현해도 가능할까요?

감사합니다.

**Comment by sangkilc** [comment]
1. Notary only allows users that have a specific set of PGP keys (Not all the students can access the notary service).

2. Yes you can.
