### ISSUE TITLE
[Team Activity] Question about changed Authentication.

### ISSUE THREAD

**Issue by pr0v3rbs** [KAIST-IS521/2017-Spring#131]
The decription of Authentication(1.7) changed with 'The server signs **the number** with its private key and encrypts **the number** with the user's public key.'

Is it right that meaning of 'encrypt(sign(random number))'?

And Can I use only encyption for sending random number? Because we will share public key on secure channel.

**Comment by soomin-kim** [comment]
We make the description more clear. Please check it.

**Comment by pr0v3rbs** [comment]
Thank you!

**Comment by jmpark81** [comment]
Initially, the encrypted data is sent to the user along with the server's public key.
According to the revised authentication, only the encrypted data is sent to the user.
Then, if the public key is generated for this activity, how does the public key send to the user?

Also, does "PGP sign and encrypt" mean the following equations?
`Encrypt(random || sign(random))`

**Comment by sangkilc** [comment]
We will put all the public keys in a git repo.

**Comment by jmpark81** [comment]
I would change the equation that I mentioned.
"PGP sign and encrypt" seems to be `Encrypt(random) || Sign (Encrypt(random))`.
