### ISSUE TITLE
[Team Activity] About openUDPSock() in SLA library

### ISSUE THREAD

**Issue by seongil-wi** [KAIST-IS521/2017-Spring#137]
DNS SLA Checker를 만들다가 궁금한 점이 있어 이슈남깁니다.

기본적으로 DNS 패킷을 전송하기 위하여 DNS SLA Checker에서는 ```openUDPSock()```함수를 이용합니다.
다음 함수를 통하여서 반환된 socket의 경우 connection과정이 없으므로 socket에 destination port와 ip는 따로 binding이 될 수 없는 상황입니다.(Connectionless 특성상 누구에게 보낼지에 대한 정보가 포함되어 있지 않은걸로 압니다)
따라서 보통 패킷을 보내거나 받을때 대표적으로 ```sendto(), recvfrom()``` 과 같은 함수를 이용하여 destination을 specify해야하는데, 본 프로젝트에서 제공되는 라이브러리의 send, recv platform은 다음과 같아서 이러한 destination을 특정짓기 어려운 상황입니다.
```c
ssiz t recvMsgUntil(int sock, const char* regex, void* buf, size t n)
```
```c
int sendMsg(int sock, const char* buf, size t n)
```

DNS SLA Checker에서의 송수신 부분에 모호함이 있어서 어떻게 해야할지 몰라 질문드립니다.

**Comment by sangkilc** [comment]
In the doc, we said:

>  The library needs to provide at least the following functionalities.

You are not limited to the number of functions to implement. You can always add a new function in your library.

**Comment by seongil-wi** [comment]
알겠습니다! 답변감사드립니다.
