### ISSUE TITLE
[Team Activity] Notary - About Launcher program

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2017-Spring#139]
In our spec:

> "The second program to write is a launcher, which takes in a certified program from the notary, and executes it only when the program is cerified"

We almost made our program but I still confused who sends the file to the launcher.
My questions are two folds:
1. Should Notary send the JSON file to the launcher? If not, who sends the JSON file?
2. Why do the launcher exist?

**Comment by jchoi2022** [comment]
> Should Notary send the JSON file to the launcher? If not, who sends the JSON file?

No, notary service is not supposed to send its output to launcher. Notary service should only communicate with a user who connected the service. Users who obtained a signature from the notary service will connect to the launcher by themselves, if they want to execute the signed file. 

> Why do the launcher exist?

Do you mean the need of launcher service is unclear? Well, please take it as we wanted to provide you a chance to experience the difficulties of implementing a securely sand-boxed environment.

**Comment by oxsignal** [comment]
Thanks to make it clear
