### ISSUE TITLE
[TeamAcitivity] About installing Docker

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2017-Spring#140]
I checked the version of our vagrant but I cannot download docker.

The version of given vagrant is 
Linux ctfbox 3.16.0-4-686-pae #1 SMP Debian 3.16.43-2 (2017-04-30) **i686** GNU/Linux

However, Docker wiki says: 
   Docker does not support **i686**

Ref :https://wiki.archlinux.org/index.php/Docker

apt-get install docker is working, but docker command is not.

Could you provide detail of installing dockers?

**Comment by blukat29** [comment]
Follow this.

```
echo 'deb http://http.debian.net/debian jessie-backports main' | sudo tee /etc/apt/sources.list.d/backports.list
sudo apt-get update
sudo apt-get install -y docker.io
sudo service docker restart
```

[source](https://github.com/jhsu802701/docker-32bit-debian-jessie-install)

**Comment by blukat29** [comment]
You can test if it works using

```
sudo docker run -it ioft/i386-ubuntu:16.04 /bin/bash
```

**Comment by oxsignal** [comment]
Thanks to giving a detail
