### ISSUE TITLE
vagrant ssh error 

### ISSUE THREAD

**Issue by nohkwak** [KAIST-IS521/2017-Spring#2]
I turned on GUI setting in Vagrantfile, by deleting annotation. 
`  config.vm.provider "virtualbox" do |vb|`
`    # Display the VirtualBox GUI when booting the machine`
`    vb.gui = true`
`  end`
So I logged in VM with the ID: vagrant , PW: vagrant. 

But, if I execute 'vagrant ssh', the error message is like following. 

$ vagrant ssh
ssh_exchange_identification: read: Connection reset by peer

Is it OK for the future activities?

**Comment by sangkilc** [comment]
Which OS are you using? What is the version of your VirtualBox and Vagrant installation?

**Comment by soomin-kim** [comment]
```
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
```
In the default Vagrantfile, there is one more line which is related with VirtualBox GUI, `vb.memory = "1024"`
But it seems that your setting file doesn't have it.
How about adding that line into your file?

**Comment by soomin-kim** [comment]
It'll be helpful for us if you upload the output that VM created while it booted up.

**Comment by nohkwak** [comment]
ubuntu 16.04 LTS, 
VirtualBox 5.0.32_Ubuntu (installed latest version for the class) 
Vagrant 1.8.1 (installed latest version for the class) 

GUI has no problem. 
But my problem is that the last step of set-up process in the lecture note (37 page) has an error. 

Thanks for your reply. 

( 01 Intro 슬라이드에서 36 페이지를 그대로 진행하면 vagrant up 에서 문제가 있어서 
  구글링을 했더니 여러가지 원인이 있을 수 있다고 하는데... 
  일단 GUI를 설정했더니... 
  VM 로긴이 가능한 창이 보입니다. 
  마지막 단계인 vagrant ssh 명령어는 위와 같은 error가 발생합니다. 
  error 잡는데 시간이 소요되어서 GUI 버전으로도 실습이 가능하다면 
  더 이상 error를 안 잡아도 될 것 같아서 문의 드립니다. )

**Comment by sangkilc** [comment]
The vagrant box we provided for this class is configured with VirtualBox version 5.1.12. Please try to use the latest version: https://www.virtualbox.org/wiki/Linux_Downloads, and see if the problem goes away.

**Comment by sangkilc** [comment]
BTW, you can just use GUI for this course.

**Comment by sangkilc** [comment]
@nohkwak Can we close this issue?

**Comment by nohkwak** [comment]
I am sorry for closing this issue, lately. 
I wanted to try to debug, again... 
If I resolve this issue, I will share the tip... 
Thanks.

**Comment by nohkwak** [comment]
I am sorry for closing this issue, lately. 
I wanted to try to debug, again... 
If I resolve this issue, I will share the tip... 
Thanks.

**Comment by ian0371** [comment]
This tortured me for days and finally I found the problem.
In guest VM, change `allow-hotplug eth0` in `/etc/network/interfaces` to `auto eth0`.
