### ISSUE TITLE
교수님 공개키.. 다운로드..

### ISSUE THREAD

**Issue by jhong3842** [KAIST-IS521/2017-Spring#52]
공개키 어디있는지 찾다가...

혼자 너무 헤매다가.. ㅠㅠ 혹시나 해서 올려요.

pgp.mit.edu에서 sangkilc@kaist.ac.kr[교수님] 메일로 검색하면

공개키 번호로 다운 받을수 있어요!!

gpg --keyserver [keyserver] --recv-key [pub id]

**Comment by jhong3842** [comment]
필요없네요...

**Comment by sangkilc** [comment]
See #50
