### ISSUE TITLE
이메일을 암호화 하는건지 궁금합니다.

### ISSUE THREAD

**Issue by jhong3842** [KAIST-IS521/2017-Spring#53]
메시지를 파일로 만든 후,
개인의 공개키로 서명하고, 교수님 공개키로 암호화
그 다음 메일로 전송하는건지 궁금합니다.
아니면 메일 자체를 서명하고 암호화해서 보내는건지 궁금합니다!

**Comment by sangkilc** [comment]
메일 자체를 서명하고 암호화 한다는 게 무슨 말인지 모르겠습니다만, 메일의 프로토콜을 바꾸라는 뜻은 아닙니다. 구글 검색을 조금만 해봐도 pgp로 메일을 암호화 하는 것이 무슨 의미인지 쉽게 알 수 있습니다.

**Comment by sangkilc** [comment]
Related question: #55
