### ISSUE TITLE
Use Inline PGP vs Use PGP/MIME

### ISSUE THREAD

**Issue by seongil-wi** [KAIST-IS521/2017-Spring#55]
과제활동을 통해 암호화한 메세지 내용을 보내기 위해 사용하는 두가지 Approach가 있음을 알게 되었습니다.

- Inline PGP는 암호화한 메세지 자체를 메일내용에 포함시키는 방식. 보내는 과정가운데 HTML formatting과 관련되어 이슈가 될 수 있음.
필자의 경우 "Message contains HTML formatting information that will be lost when converting to plain text for signing/encryption. Do you wish to proceed?"라는 alert dialog가 나옴.

- PGP/MIME는 암호화한 메일의 내용자체를 .asc파일로 converting한후 첨부하는 방식

본 과제활동에서의 결과물제출 방법으로 Inline PGP보다는 PGP/MIME Apporach를 채택하는 것이 더 적합할까요?

**Comment by SeungwonWoo** [comment]
저도 이 부분이 궁금합니다.

추가로 질문의 PGP/MIME Apporach 방식이 .asc파일로 바꾼 뒤 메시지 자체를 메일내용에 포함시키는 방식을 뜻하는 건가요? 아니면 .asc파일로 바꾼 뒤 해당 파일을 첨부파일로 보낸다는 것을 말하는 건가요? 후자의 경우면 굳이 .asc파일로 바꾸지 않고 바로 첨부하면 되지 않나 싶네요.

**Comment by sangkilc** [comment]
You can use any approach, but the second approach is better than the first one. There's no reason to mix plain text with ciphertext.
