### ISSUE TITLE
I can't compile '0313-backdoor.tex' file

### ISSUE THREAD

**Issue by pr0v3rbs** [KAIST-IS521/2017-Spring#57]
윈도우에서 TeXworks 설치해서 사용하고 있습니다.
그런데 '0313-backdoor.tex' 파일이 컴파일 되지 않습니다.

'console output' 에는 다음과 같이 나옵니다.
![default](https://cloud.githubusercontent.com/assets/8536529/23821137/eddcefc6-066c-11e7-91bf-f644d1ad73e1.PNG)

로그파일에는 다음과 같이 적혀있습니다.
2017-02-27 16:31:23,437+0900 INFO  texify - running 'initexmf --quiet --update-fndb' to refresh the file name database

그래서 해당 명령어를 입력해보았는데도 컴파일이 되지 않습니다.

추가로 tex내의 '\bibliography{references}' 라인을 주석처리 하니 정상적으로 컴파일 됩니다.

**Comment by pr0v3rbs** [comment]
아.. citation commands가 없어서 컴파일이 안되는 것 같습니다.

**Comment by sangkilc** [comment]
You should ignore the file at this point. It will be updated on Monday.
