### ISSUE TITLE
Questions about Trust Level

### ISSUE THREAD

**Issue by SeungwonWoo** [KAIST-IS521/2017-Spring#58]
안녕하세요.
제가 저번 Key-Signing Party를 진행할 때 노트북의 일부 설정이 잘못되어 일찍 돌아가게 되었습니다.
그래서 아무와도 키 교환을 하지 못했습니다.

1. Key-Signing의 Minimum 제한이 있나요? 있다면 self-sign을 제외한 몇 명의 서명이 최소 기준인가요?
2. 과제에서 4번의 Sending an encrypted E-mail에서 반드시 제 서명을 trusted signature로 만든 후에 서명해야 하나요?

이상입니다.

**Comment by sangkilc** [comment]
1. I didn't set the minimum requirement. See the answer below.
2. If you generated your key by yourself, it will have trust level 4 by default.

**Comment by sangkilc** [comment]
Actually, about your first question, the minimum requirement would be *one*. In other words, you need to get a signature from a person other than you, then you will be fine.

**Comment by SeungwonWoo** [comment]
Thank you.
