### ISSUE TITLE
[Activity #3] spec of puts instruction

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/2017-Spring#65]
In a document, behavior of puts is described as libc puts function.

But I think that it is impossible to implement a pseudocode listed at "Listing 1".
In a detail, `printf("User: ");` doesn't print any new line char, but libc puts function always prints new line character at the end of output.

So I suggest a new spec that is same with libc puts except new line char.

**Comment by sangkilc** [comment]
That's really a good point. The tex is fixed, and I close the issue.
