### ISSUE TITLE
Question about size of operands

### ISSUE THREAD

**Issue by ian0371** [KAIST-IS521/2017-Spring#66]
*ite* and *jump* opcodes have immediate value(s) as operand.
I guess the size of *ite*'s operand (immediate value) is 1 byte.
Is the size of *jump*'s operand also 1 byte?

If so, is it okay to assume that the size of code does not exceed 1024 bytes? (at most 256 instructions, each being 4 bytes)

**Comment by sangkilc** [comment]
Yes, I believe 256 instructions are enough for the purpose of this assignment.
