### ISSUE TITLE
Backdoor Detection Logic 

### ISSUE THREAD

**Issue by nohkwak** [KAIST-IS521/2017-Spring#67]
backdoor가 동작되는 기준이 

1) Interpreter가 본인이 짠 login 프로그램에서만 동작하도록 특정 패턴을 찾아야 하나요? 
2) 아니면 다른 사람이 개발한 login 프로그램에서도 backdoor가 동작해야 하나요?  
   (login 프로그램 또는 compiler가 버전업 될 수 있다는 상황 고려) 
3) 슈퍼키처럼 "superuser"가 입력되면 어떤 프로그램에서도 embed된 backdoor 로직을 실행하게 해도 되나요? 

강력한 backdoor라고 가정하고 3)으로 구현했는데... 
혹시 해석상의 차이로 감점을 당하지 않을지 걱정되어서 문의 드립니다.

**Comment by mikkang** [comment]
1번 같아 보이네요. 아니라면 난이도 상승..ㅠ
'when you use a user ID "superuser", then this backdoor allows...' 라고 되어 있으니 login ID가 superuser일 때만 bypass 해야 할 것 같습니다.

**Comment by sangkilc** [comment]
In the description:
> create a backdoor in the interpreter, which can detect your login program.

If you can do (2) or (3) in a general fashion, we may give you extra points, although it seems extremely difficult 😄
