### ISSUE TITLE
Question for smart way to fix bug

### ISSUE THREAD

**Issue by mikkang** [KAIST-IS521/2017-Spring#68]
I fixed bug in my interpreter code after copy my previous code to the backdoor folder.
Is there a good way to apply both?
diff is not helpful to me.

**Comment by nohkwak** [comment]
그냥 제 개인적인 생각은 interpreter.c를 쪼개지 않는다는 가정에서

#define BACKDOOR  
#ifdef BACKDOOR

#endif BACKDOOR
를 활용하시어 하나의 파일로 관리하시거나

전처리하는 컨셉으로
backdoor 쪽 코드의 주석에 특정 패턴을 넣고 
ex) /* --start--*/
       삭제될 코드
       /*--end--*/
스크립트로  interpreter 쪽에 copy 하면서 
line by line 으로 삭제될 코드를 지우는 것은 어떨까요?


2017. 3. 17. 오전 2:04 mikkang <notifications@github.com> 작성:

**Comment by sangkilc** [comment]
You can create a backdoor branch in your local, and then copy your backdoor right before the submission.
