### ISSUE TITLE
Enquiry about pgp key update.

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2017-Spring#70]
During PGP activity,  I updated my mail address of my pgp key after signed from 4 classmates
(There is some typo in my email address. I noticed it after signed).

I have not checked  my activitiy score so I wonder there is any penalty on my case.

**Comment by soomin-kim** [comment]
Actually, in our grading criteria, it doesn't matter whether your e-mail address is correct or not.
Of course, the correctness of your e-mail address is important for real situations,
but this activity teaches how to generate PGP key.
So, please don't worry :)

**Comment by oxsignal** [comment]
Thanks for clear explanation.
