### ISSUE TITLE
worm activity 질문

### ISSUE THREAD

**Issue by asdfljh** [KAIST-IS521/2017-Spring#71]
과제 3.1에 4번을 보면
For the purpose of this exercise, we just close
the connection at this point without running the worm binary, but in reality, you
would run the binary. N.B., we will deduct points if you execute the worm after
propagation.
라는 부분이 있는데요.

이 말이 실제와는 다르게 과제에서는 worm을 시작하는 호스트에서만 propagation이 발생하고 감염된 호스트들에서는 따로 propagation이 이뤄지면 안된다는 의미인가요?

**Comment by soomin-kim** [comment]
Yes. Since propagated binaries will not be executed by infected computers.

**Comment by sangkilc** [comment]
Yes, simply make it more unreal to make our (course staffs) life easier.
