### ISSUE TITLE
Octal IP address?

### ISSUE THREAD

**Issue by asdfljh** [KAIST-IS521/2017-Spring#73]
이상한(?) 질문일수도 있지만, myworm의 인자로 ip주소가 192.168.023.048 이런식으로 들어올 수도 있나요?
찾아보니까 특정함수를 사용할 경우 023, 048을 octal로 인식해서 계산을 해주더군요...

저런 이상한 입력에 대하여 invalid하다고 처리해야하는지, 아니면 앞에 0이 없다고 생각하고 처리(위의 예시는192.168.23.48로 처리)해야하는지 궁금합니다.

**Comment by sangkilc** [comment]
We will not consider octal ip addresses for this assignment.
