### ISSUE TITLE
/proc/ in mac

### ISSUE THREAD

**Issue by mickan921** [KAIST-IS521/2017-Spring#74]
After debugging for a while, I realized that /proc/ does not exist in MacOS.

Is there another way for Mac users..?

thanks

**Comment by DaramG** [comment]
I think vulnet is running on Linux, so you should test it on Linux, not macOS.

**Comment by sangkilc** [comment]
Why don't you use the VM that we provided in the class? We always assume that you are using Linux throughout this course.
