### ISSUE TITLE
[Activity 4] .gitignore file

### ISSUE THREAD

**Issue by mfaerevaag** [KAIST-IS521/2017-Spring#77]
This might be a dumb question, but is it allowed to use a `.gitignore` file instead of just not committing the `build/myworm` binary?

The reason for me asking is that the activities are always very precise on final deliverables and usually deduct point if the delivery deviates from the specification.  Activity 4 lists three files, `README.md`, `src/` and `Makefile`, and specifically states that binary should not be commited. The usual way is using a `.gitingore` file, but this would add a fourth file.

**Comment by ian0371** [comment]
I don't think it matters to commit it or not, but how about not staging `.gitignore`?

**Comment by sangkilc** [comment]
You can use .gitignore files. The spec includes 2 sets: a) a set of files/dirs we expect, and b) a set of files that should not be included. In fact, ```.gitignore``` is not in either set.

**Comment by mfaerevaag** [comment]
@ian0371 Thanks for the tip. I guess that would limit the amount of untracked files listed when doing, for instance, `git status`.

I could of course just not track what I want to ignore, but as there is several files it makes the tracking cluttered. Also there is risk of accidentally committing security critical files (API keys etc), which should not be version controlled.
