### ISSUE TITLE
libyara-dev version(?) in provided VM

### ISSUE THREAD

**Issue by asdfljh** [KAIST-IS521/2017-Spring#84]
수업에서 제공된 VM에서 libyara-dev를 설치했는데 버전을 확인해보니 3.1.0입니다.

주어진 scanner.c 코드를 보면
`yr_compiler_set_callback() compiler, cbCompile, NULL );` 이 있는데
[libyara 3.1.0 docs](http://yara.readthedocs.io/en/v3.1.0/capi.html#c.yr_compiler_set_callback)에는 yr_compiler_set_callback함수가 인자가 2개뿐입니다. (void *user_data가 빠져있습니다.)
이 경우는 별 상관이 없을 것 같긴 하지만, 버전별로 차이가 있을것으로 생각되어서 질문드립니다.

기준이 되는 yara version이 있을까요?

**Comment by sangkilc** [comment]
Since I did not specify the version, you can use any version you want for this activity. I will talk specifically about this issue in the next class. Thank you for pointing this out.

**Comment by jmpark81** [comment]
In my case, `libyara-dev` 2.0.0 was installed on my Ubuntu 14.04.1 VM via `sudo apt-get install libyara-dev`.
According to the reference cited in the activity file, version 3.4.0 seems to be the specification.
Thus, I manually built and installed version 3.4.0 from [here](https://github.com/plusvic/yara/releases).

**Comment by sangkilc** [comment]
Ah, right, I used the explicit citation to the verion 3.4.0. So I think we can stick to the version. Will talk about this again in the next class. Thank you for your comment.
