### ISSUE TITLE
Does myworm.yr include all variants of myworm?

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/2017-Spring#85]
The signatures of `myworm-`s  in the zip file seem to be various.
For example, the default output file should be `slaves.csv` according to the specification.
However, some worms are using different file names (_e.g.,_ `slave.csv`, `juicy.csv`).

Should YARA rule include all these variations to detect if provided `myworm-` or not?

**Comment by sangkilc** [comment]
Please see #81. It defines the meaning of being the myworm family. I also updated the activity document.
