### ISSUE TITLE
how to install "hash" module in yara

### ISSUE THREAD

**Issue by mikkang** [KAIST-IS521/2017-Spring#86]
There are some useful modules in yara. 
Some modules are installed default and not the rest.

Has anyone used "hash" module?

I have an error message: unknown module "hash". 
This is documentation to install: http://yara.readthedocs.io/en/v3.5.0/modules/hash.html
I did above instruction. but, I still can not use it.

I use given vagrant in the class and yara v3.5

**Comment by dinggul** [comment]
Yes, I had

Would you try this yara rule file?
```
import "hash"

rule MD5_compare {
meta:
    description = "yay"

condition:
    hash.md5(0, filesize) == "fa69404d4e478bddecdd71c8d51d9f54"
}
```

**Comment by mikkang** [comment]
I tried above rule file, but I still have: `unknown module "hash"`

I think there is some problem in install process.
I installed following
<pre>
$ sudo apt-get install libssl-dev
$ cd [my yara source dir]
$ ./configure --with-crypto
$ make
$ sudo make install
</pre>
Do you have any additional command to install?

**Comment by dinggul** [comment]
I can't understand your installing process

Why is there both 'apt' and './configure ~~~' for installing libssl-dev?
In my case, I just installed using apt, no more additional command

**Comment by dinggul** [comment]
Oh, is that for installing yara?

**Comment by mikkang** [comment]
yes, sorry for confusing. I changed it

**Comment by dinggul** [comment]
I just installed yara with apt... I will not be helpful. sorry :(

**Comment by sangkilc** [comment]
BTW, our activity document has an explicit citation to yara version 3.4.0. So I recommend you to use 3.4.0.

**Comment by mikkang** [comment]
Okay, thank you. 
And I will try with yara version 3.4

**Comment by mikkang** [comment]
Oh.. I solved it.
Actually, I installed yara via `apt-get install ` command first.
but due to debian package version, I installed again via compiling sources.
 
I think, there is something twisted in above process. 
To downgrade yara version 3.4, I removed all files related yara, and re-installed.
then, I don't have a problem anymore.
