### ISSUE TITLE
[Suggestion] What makes my points deducting

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/2017-Spring#87]
In our grades-* repository, only grading criteria and score is uploaded

But sometimes, I confused which one is my missing since there are several subjective criteria such as 'If the code is difficult to read and understand'.
So if I'd like to check exact criteria making my points deducting, I should ask to TA, but I think it is uncomfortable for both.

So my suggestion is, uploading a O/X table for each criterion.
It also gives enough time for students to think what was wrong from previous activities and check whether it is wrong or not.

**Comment by sangkilc** [comment]
I agree with you. I am also getting too many emails regarding scores.

**Comment by sangkilc** [comment]
Further, we already have such tables in our google doc. It should be easy for TAs to do so.

**Comment by dinggul** [comment]
I hope it is applied from next grading :)
