### ISSUE TITLE
When a user specifies at least one directory..

### ISSUE THREAD

**Issue by seongil-wi** [KAIST-IS521/2017-Spring#89]
I just confused about this description.
> Second, when a user specifies at least one directory to scan, then you simply recursively enumerate and scan all the files in the directory.

1. When I specifies the directories after specifying rule file, Is it right to specify a "directory name" only?
If so, how is the path set? 
Do I need to specify the directory that contains the path?

2. It is very simple question. If there is a directory in the specified directory, about scan, can I just ignore it?

**Comment by sangkilc** [comment]
1. A path can be either relative or absolute.
2. That's why you need to 'recursively' scan a given directory. Suppose a directory X has two subdirectories: X/a and X/b. When you scan X, you should recursively scan all files in X, X/a, and X/b.

**Comment by seongil-wi** [comment]
I understood well!! Thank you for answer.
