### ISSUE TITLE
Vulnet full request confuse

### ISSUE THREAD

**Issue by jhong3842** [KAIST-IS521/2017-Spring#90]
The recvSock of vulnet has been modified,

Commit: 0bdfcf5a45b496e35e5be554410480bea96adabc

When I tested it during homework, it works correctly in the version before modification.

When creating a variant worm, what version should I test?

Also, do I need to modify myworm to match the current version for Activity4?

**Comment by sangkilc** [comment]
I already mentioned this problem in the previous class. You should always use the latest version. You should update your worm for activity 4.
