### ISSUE TITLE
64-bit worms does not run on 32-bit system

### ISSUE THREAD

**Issue by ian0371** [KAIST-IS521/2017-Spring#91]
Two worm files are compiled in 64-bit and thus does not run on the provided vagrant vm.
Those files can be easily checked by the following command:
```bash
$ file * | grep 64-bit
```

**Comment by sangkilc** [comment]
TAs will handle this problem. Thanks for notifying this problem.

**Comment by sangkilc** [comment]
Please check the latest commit.

**Comment by ian0371** [comment]
Thanks.
