### ISSUE TITLE
Is the scanner needed to handle thousands of files?

### ISSUE THREAD

**Issue by donghwan17** [KAIST-IS521/2017-Spring#92]
When I scan files recursively with 'scanDir', 'opendir' function is failed after scanning thousands of files. 
The error message said "Too many open files". 

If our mission is only considering limited number, 90, of files, my scanner looks fine.
Is my scanner needed to handle thousands of files?

**Comment by sangkilc** [comment]
It means your implementation has a bug of not closing file desriptors.
