### ISSUE TITLE
Problem for return value of yr_rules_scan_file

### ISSUE THREAD

**Issue by jcassoumounat** [KAIST-IS521/2017-Spring#93]
About yara's functions : 
When I start the function x = yr_rules_scan_file(rules, dir, SCAN_FLAGS_FAST_MODE, callback_function, NULL, 0); in order to scan my file, the value x that I have is always  
CALLBACK_MSG_SCAN_FINISHED. Isn't it suppose to give the two messages CALLBACK_MSG_RULE_MATCHING or CALLBACK_MSG_RULE_NOT_MATCHING ?

**Comment by asdfljh** [comment]
The function yr_rules_scan_file doesn't return that messages. You can see these messages in your callback_function.
[yr_rules_scan_file documentation]:https://yara.readthedocs.io/en/v3.4.0/capi.html#c.yr_rules_scan_file

**Comment by jcassoumounat** [comment]
Should I call the callback_function after the scan ?

**Comment by nohkwak** [comment]
First,  you define callback function like the following ....

int callback_function( int message, void* message_data, void* user_data)
{
...
}

then, you can pass that function as 4th parameter when you call
yr_rules_scan_file.


2017-03-31 17:18 GMT+09:00 Jean Cassou-Mounat <notifications@github.com>:

**Comment by jcassoumounat** [comment]
Yes but passing the function in parameters doesn't make a call of this function, isn't it ?

**Comment by nohkwak** [comment]
Sorry. I don't know why...

But I just recommend...

  yr_rules_scan_file(
    rules,
    file,
     0 /* no SCAN_FLAGS_FAST_MODE */ ,
    callback_function,
    user_data,
    0 /* no timeout */ )

1. At first, test with the simple yara rule...
2. check the file path
3.  check the option

In my case, 1 and 2 were the main reason.

2017-03-31 17:46 GMT+09:00 Jean Cassou-Mounat <notifications@github.com>:

**Comment by jcassoumounat** [comment]
Ok thanks, I will try :)

**Comment by jcassoumounat** [comment]
I made it simple as possible : yr_rules_scan_file( rules, file, 0, callback_function, NULL, 0) and verified the path of the file which is good and still doesn't work....

**Comment by mickan921** [comment]
Are you saying that u cannot verify the file path inside the yr_rules_scan_file() function?

**Comment by oxsignal** [comment]
In yr_rules_scan_file function, second argument should be character, not FILE descriptor.

Refer to:
int yr_rules_scan_file(YR_RULES* rules, const char* filename, int flags, YR_CALLBACK_FUNC callback, void* user_data, int timeout)

If you wish to use file descriptor, you should use "yr_rules_scan_fd" (refer to yara manual). 

Example : 
FILE *fp;
char buffer[] = "/tmp/file;
fp =fopen(buffer,"rb");
// Add some exception handling in case file does not exist
yr_rules_scan_file(rules,buffer,0,callback,NULL, 0);

**Comment by jcassoumounat** [comment]
For me it wasn't working with the entire path but I had to copy the file into the current repository and to analyse it here....
