### ISSUE TITLE
Function yr_rule_scan_file - exit with "killed" message

### ISSUE THREAD

**Issue by asdfljh** [KAIST-IS521/2017-Spring#94]
수업에서 주어진 box로 만들어진 VM에 vagrant ssh로 접속했을 때, 저의 경우엔 /vagrant에 deb32-jessie-base-vb5.1.12.box가 있어서 yr_rules_scan_file을 통해 scan을 진행해보았는데 "killed"라는 메시지와 함께 scanner가 종료됩니다.

여러 테스트를 해봤지만 확실한 원인을 알수 없었고, 한 가지 의심해본 부분이 파일사이즈가 870MB정도 되는데 VM 메모리가 작아서 kill되는 시나리오였는데, 다른 OS를 쓰는 VM(메모리 512MB)에서는 yr_rules_scan_file이 동작하길래 질문드립니다.

다른 환경에서는 정상 동작해서 코딩 실수가 아닌 다른 요소가 원인일거라고 추측하고 있습니다.

원인을 찾아보다가 너무 모르겠어서 질문드립니다. 의심되는 부분에 대해 의견주시면 확인해보겠습니다.

그리고, 저처럼 수업에서 주어진 vagrant box 설정 그대로 쓰시는 분들이 있으시다면, box파일을 vm에 올려놓고 scan 테스트 해주실수 있을까요?

**Comment by sangkilc** [comment]
If you are using the default setting of the vagrant box, your process can be sigkilled due to the small memory footprint. You can increase the RAM size by modifying ```Vagrantfile```.
