### ISSUE TITLE
[Activity 4] question about print out scan result(File Name)

### ISSUE THREAD

**Issue by pr0v3rbs** [KAIST-IS521/2017-Spring#95]
There is a specification for print of scan result in document.(2.3.)

I think that the meaning of 'File Name' is **not full path(only file name)**.

But some people said that it is not intuitive.

Is it right that print out only file name?

**Comment by sangkilc** [comment]
Can you elaborate your question? What do you mean by not intuitive? Who are some people?

**Comment by pr0v3rbs** [comment]
I'm sorry that I didn't explain in detail.

**Meaning of not intuitive** : If we are not using full path(using only file name). When program detects some malwares, then we can't know full path about malware. (It could be the same file name in another location.)

**Meaning of some people** : me & friends.

Finally I want to know : **Is it right that print out only file name, when scan files?**

Thank you.

**Comment by ian0371** [comment]
I had the same question. I wonder if it's okay to print file name including relative or absolute path or I should just print the file name itself.

**Comment by sangkilc** [comment]
I see. Using an absolute file name makes more sense as you mentioned, but it is okay to use either absolute or relative file names, since I did not specify it in the doc.

**Comment by pr0v3rbs** [comment]
Thank you for your answer.
