### ISSUE TITLE
My worm file is not working properly

### ISSUE THREAD

**Issue by seongil-wi** [KAIST-IS521/2017-Spring#96]
myworm-seongil-wi in the given worm-bins.zip file is not working correctly. 
It is also different from a binary file compiled with source code that I submitted to my private repository.
(I used the most recent version of vulnet)

Please confirm. 
Thank you.

**Comment by seongil-wi** [comment]
I guess, binary file seems to have behaved differently because I specified the file path as ".myworm" rather than argv [0] in self-replication....right?

**Comment by sangkilc** [comment]
TAs will be able to answer this question in more detail, but I will give some general comments.

- When you say two binaries are different, I guess it means their hash values are different? If so, this is normal. Two different compilers can produce two different binaries from the same source code.
- Hardcoding a path in a program is not a good programming practice.

**Comment by jae519** [comment]
Dear seongil-wi,

Hello, I'm one of the TA of the worm assignment. 

I don't know what is the exact meaning of "not working correctly." but your worm compiles and runs correctly in our test environment.

Thanks.

**Comment by seongil-wi** [comment]
Perhaps the file path does not seem to work correctly. The name of the supplied binary file is "myworm-seongil-wi". However, the path I specified for self-replication is .myworm. This is why the file does not seem to work well. Actually, this is a problem not only with my file, but also with some of the binary files provided.

Professor. Thank you for your advice.

Thanks.
