### ISSUE TITLE
[worm activity] May we use `libprocps`?

### ISSUE THREAD

**Issue by mfaerevaag** [KAIST-IS521/2017-Spring#97]
As for getting all running processes the activity hints to the `ps` source code. May be use the `libproc`, as `ps` does, or should we include necessary code with the scanner binary?

The provided vagrant box includes `libprocps.so.3.0.0`, though I am unable to find the header files.

**Comment by sangkilc** [comment]
You can use any approach you want. If you want to use the lib, you can install [libprocps3-dev](https://packages.debian.org/jessie/libprocps3-dev). But, when you use such lib, I recommend you to add an installation script in your Makefile to make course staffs happier.

**Comment by mfaerevaag** [comment]
Understood! Thank you.
